#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import random
import sys

sys.path.append('.')
import library

combination=random.randint(100,999)
counter=0

done=False
while not done:
    guess=library.GetUserNumber("What is your guess (enter a number from 100-999)? ")
    if guess>combination:
        print("Too high")
        counter+=1
    elif guess<combination:
        print("Too low")
        counter+=1
    else:
        print("You got the combination! It took",counter,"guesses")
        done=True
