#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import random
import sys
import os
from datetime import datetime

# Convience variables

if len(sys.argv)>=3:
    StartNumber=int(sys.argv[1])
    EndNumber=int(sys.argv[2])
else:
    print("Need a starting and ending number")
    sys.exit(0)

# Get combination
# if combination file exists, read it

if os.path.exists('combination.txt'):
    FileHandle=open('combination.txt','r')
    combination=int(FileHandle.readline())
    FileHandle.close()
else:
    combination=random.randint(StartNumber,EndNumber)
    FileHandle=open('combination.txt','w')
    FileHandle.write(f"{combination}\n")
    FileHandle.close()

# Build trial list

number=StartNumber
NumberList=[]

while number<EndNumber+1:
    NumberList.append(number)
    number+=1

# Try to guess combination

counter=0
startTime=datetime.now()
done=False
while not done:
    trial=random.randint(0,len(NumberList)-1)
    guess=NumberList[trial]
    if guess==combination:
        done=True
    else:
        NumberList.pop(trial)
        counter+=1
endTime=datetime.now()

elapsedTime=endTime-startTime

print(f"Combination found: {guess}. It took {counter} tries in {elapsedTime}.")
